function Hd = untitled
%UNTITLED Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.1 and the DSP System Toolbox 8.4.
% Generated on: 10-Jul-2016 16:29:47

% FIR constrained equiripple Highpass filter designed using the FIRCEQRIP
% function.

% All frequency values are in Hz.
Fs = 2500;  % Sampling Frequency

N     = 80;              % Order
Fc    = 70;              % Cutoff Frequency
slope = 0;               % Stopband Slope
Dstop = 1e-05;           % Stopband Attenuation
Dpass = 0.057501127785;  % Passband Ripple

% Calculate the coefficients using the FIRCEQRIP function.
b  = firceqrip(N, Fc/(Fs/2), [Dstop, Dpass], 'slope', slope, 'min', ...
               'high');
Hd = dfilt.dffir(b);

% [EOF]
