function Hd = untitledFilt
%UNTITLEDFILT Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.1 and the DSP System Toolbox 8.4.
% Generated on: 07-Jul-2016 13:43:21

% FIR constrained equiripple Highpass filter designed using the FIRCEQRIP
% function.

% All frequency values are normalized to 1.

N     = 140;               % Order
Fc    = 0.035;             % Cutoff Frequency
slope = 0;                 % Stopband Slope
Dstop = 3.1622776602e-05;  % Stopband Attenuation
Dpass = 0.057501127785;    % Passband Ripple

% Calculate the coefficients using the FIRCEQRIP function.
b  = firceqrip(N, Fc, [Dstop, Dpass], 'slope', slope, 'min', 'high');
Hd = dfilt.dffir(b);

% [EOF]
